import { defineConfig } from 'tsup';
import Vue from 'unplugin-vue/esbuild';

// The SFC compile step is the only build cost the Vue adapter adds (DD-012). Types come
// from vue-tsc, which understands `.vue` files.
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'line-chart': 'src/line-chart.ts',
    'bullet-chart': 'src/bullet-chart.ts',
    'pyramid-chart': 'src/pyramid-chart.ts',
    'heatmap-chart': 'src/heatmap-chart.ts',
    'treemap-chart': 'src/treemap-chart.ts',
    'sankey-chart': 'src/sankey-chart.ts',
    'activity-grid': 'src/activity-grid.ts',
    'step-chart': 'src/step-chart.ts',
    'sparkline-rows': 'src/sparkline-rows.ts',
    'kpi-card': 'src/kpi-card.ts',
    'bar-chart': 'src/bar-chart.ts',
    'stacked-bar-chart': 'src/stacked-bar-chart.ts',
    'composed-chart': 'src/composed-chart.ts',
    'waterfall-chart': 'src/waterfall-chart.ts',
    'funnel-chart': 'src/funnel-chart.ts',
    'candlestick-chart': 'src/candlestick-chart.ts',
    'area-chart': 'src/area-chart.ts',
    'range-band-chart': 'src/range-band-chart.ts',
    'stream-chart': 'src/stream-chart.ts',
    'scatter-chart': 'src/scatter-chart.ts',
    'bubble-chart': 'src/bubble-chart.ts',
    'donut-chart': 'src/donut-chart.ts',
    'radar-chart': 'src/radar-chart.ts',
    'polar-bar-chart': 'src/polar-bar-chart.ts',
    'radial-arc-group': 'src/radial-arc-group.ts',
    'radial-rings': 'src/radial-rings.ts',
    'gauge-arc': 'src/gauge-arc.ts',
    'meter-chart': 'src/meter-chart.ts',
    'coxcomb-chart': 'src/coxcomb-chart.ts',
    'wind-rose': 'src/wind-rose.ts',
    'volvelle-chart': 'src/volvelle-chart.ts',
    'chord-ring': 'src/chord-ring.ts',
    'orbit-chart': 'src/orbit-chart.ts',
  },
  format: ['esm'],
  target: 'es2022',
  dts: false,
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: ['vue', '@silverpoint/core', '@silverpoint/grounds'],
  esbuildPlugins: [Vue()],
});
