/**
 * The canonical form of the Art. 3 string gate (DD-004). Markup is parsed with a conforming
 * HTML parser and compared as a tree — tag, sorted attributes, numbers at 2 decimals, text with
 * entities resolved — so attribute order, self-closing style and entity spelling fall outside
 * the contract by construction, instead of being patched by substitutions.
 */
import { parseFragment, type DefaultTreeAdapterMap } from 'parse5';

type ParsedNode = DefaultTreeAdapterMap['childNode'] | DefaultTreeAdapterMap['documentFragment'];
type ParsedElement = DefaultTreeAdapterMap['element'];

export interface NormalElement {
  readonly tag: string;
  readonly attrs: readonly (readonly [string, string])[];
  readonly children: readonly NormalNode[];
}
export type NormalNode = NormalElement | { readonly text: string } | { readonly comment: string };

/**
 * Comments that are a framework's hydration markers, by explicit, versioned list (DD-017): Vue's
 * fragment and `v-if` anchors, Angular's container anchors and hydration marks. Any other comment
 * in a dashboard is content, and a difference.
 */
const HYDRATION_MARKERS = new Set(['[', ']', 'v-if', '', 'container', 'ng-container', 'ngh']);
const HYDRATION_MARKER_PATTERNS = [/^bindings=\{/];
const isHydrationMarker = (text: string) => HYDRATION_MARKERS.has(text.trim()) || HYDRATION_MARKER_PATTERNS.some((p) => p.test(text.trim()));

/** Angular's component host elements (`<sp-line-chart>`, `<sp-chart-frame>`…): React and Vue write none. */
const ANGULAR_HOST = /^sp-[a-z-]+$/;

interface TreeOptions {
  /** DD-017: keep non-marker comments, unwrap Angular hosts, compare `style` as declarations. */
  readonly dashboard: boolean;
}

/**
 * Attributes a framework injects, filtered by explicit, versioned list. A new one breaks the
 * gate until someone adds it here deliberately — the desired behaviour (DD-004).
 */
const FILTERED_NAMES = new Set(['ng-version', 'ngh', 'ngskiphydration']);
const FILTERED_PREFIXES = ['_ngcontent-', '_nghost-', 'ng-reflect-'];

/**
 * Id tokens generated by a framework rather than derived from props, per adapter: React ≥ 19.2
 * `useId()` (`_r_0_`), Vue `useId()` (`v-0`), and the Angular adapter's instance counter
 * (`ng0`). They normalise to a stable counter; every other id is compared verbatim.
 */
const GENERATED_ID_TOKENS = [/_r_[0-9a-z]+_/gi, /\bv-\d+\b/g, /\bng\d+\b/g];

/** Attributes whose values are numbers or number lists, compared at 2 decimals (REQ-002). */
const NUMERIC = new Set(['d', 'x', 'y', 'x1', 'x2', 'y1', 'y2', 'cx', 'cy', 'r', 'width', 'height', 'viewBox', 'points', 'transform', 'patternTransform']);
const NUMBER = /-?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?/g;

function round2(value: number): string {
  const rounded = Math.round(value * 100) / 100;
  return String(Object.is(rounded, -0) ? 0 : rounded);
}

function isElement(node: ParsedNode): node is ParsedElement {
  return 'tagName' in node;
}

function findChartSvg(node: ParsedNode): ParsedElement | undefined {
  let first: ParsedElement | undefined;
  const visit = (current: ParsedNode): ParsedElement | undefined => {
    if (isElement(current) && current.tagName === 'svg') {
      const classes = current.attrs.find((attr) => attr.name === 'class')?.value.split(/\s+/) ?? [];
      if (classes.includes('sp-chart')) return current;
      first ??= current;
    }
    for (const child of 'childNodes' in current ? current.childNodes : []) {
      const found = visit(child);
      if (found) return found;
    }
    return undefined;
  };
  return visit(node) ?? first;
}

function filtered(name: string): boolean {
  return FILTERED_NAMES.has(name) || FILTERED_PREFIXES.some((prefix) => name.startsWith(prefix));
}

/** `style` as its declarations, in order, each `name:value` with numbers at 2 decimals (DD-017). */
function styleDeclarations(value: string): string {
  return value
    .split(';')
    .map((declaration) => declaration.trim())
    .filter(Boolean)
    .map((declaration) => {
      const colon = declaration.indexOf(':');
      const name = declaration.slice(0, colon).trim();
      const body = declaration.slice(colon + 1).trim().replace(NUMBER, (token) => round2(Number(token)));
      return `${name}:${body}`;
    })
    .join(';');
}

function childNodes(element: ParsedElement, options: TreeOptions, ids: Map<string, string>): NormalNode[] {
  const children: NormalNode[] = [];
  for (const child of element.childNodes) {
    if (isElement(child)) {
      if (options.dashboard && ANGULAR_HOST.test(child.tagName)) children.push(...childNodes(child, options, ids));
      else children.push(toTree(child, ids, options));
    } else if (child.nodeName === '#text' && 'value' in child) {
      const text = child.value.replace(/\s+/g, ' ').trim();
      if (text.length > 0) children.push({ text });
    } else if (options.dashboard && child.nodeName === '#comment' && 'data' in child && !isHydrationMarker(child.data)) {
      children.push({ comment: child.data.trim() });
    }
  }
  return children;
}

function toTree(element: ParsedElement, ids: Map<string, string>, options: TreeOptions = { dashboard: false }): NormalElement {
  const attrs = element.attrs
    .filter((attr) => !filtered(attr.name))
    .map((attr) => {
      let value = attr.value.trim().replace(/\s+/g, ' ');
      if (NUMERIC.has(attr.name)) value = value.replace(NUMBER, (token) => round2(Number(token)));
      if (options.dashboard && attr.name === 'style') value = styleDeclarations(value);
      for (const pattern of GENERATED_ID_TOKENS) {
        value = value.replace(pattern, (token) => {
          if (!ids.has(token)) ids.set(token, `gen${ids.size}`);
          return ids.get(token) as string;
        });
      }
      return [attr.name, value] as const;
    })
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return { tag: element.tagName, attrs, children: childNodes(element, options, ids) };
}

/** Parses markup and returns the normalised tree of its chart `<svg>`. */
export function parseSvg(markup: string): NormalElement {
  const svg = findChartSvg(parseFragment(markup));
  if (!svg) throw new Error('No <svg> element in the markup.');
  return toTree(svg, new Map());
}

function lines(node: NormalNode, depth: number, out: string[]): void {
  const indent = '  '.repeat(depth);
  if ('comment' in node) {
    out.push(`${indent}<!--${node.comment}-->`);
    return;
  }
  if ('text' in node) {
    out.push(`${indent}${JSON.stringify(node.text)}`);
    return;
  }
  const attrs = node.attrs.map(([name, value]) => ` ${name}=${JSON.stringify(value)}`).join('');
  out.push(`${indent}<${node.tag}${attrs}>`);
  for (const child of node.children) lines(child, depth + 1, out);
}

/** The normalised form as text, one node per line: what a fixture's canonical file holds. */
export function normalizeSvg(markup: string): string {
  const out: string[] = [];
  lines(parseSvg(markup), 0, out);
  return out.join('\n');
}

function label(node: NormalNode): string {
  return 'comment' in node ? '#comment' : 'text' in node ? '#text' : node.tag;
}

function difference(actual: NormalNode, expected: NormalNode, path: string): string | undefined {
  if ('comment' in actual || 'comment' in expected) {
    if ('comment' in actual && 'comment' in expected && actual.comment === expected.comment) return undefined;
    return `${path}: ${label(actual)} ≠ ${label(expected)}`;
  }
  if ('text' in actual || 'text' in expected) {
    if ('text' in actual && 'text' in expected && actual.text === expected.text) return undefined;
    return `${path}: ${JSON.stringify('text' in actual ? actual.text : `<${actual.tag}>`)} ≠ ${JSON.stringify('text' in expected ? expected.text : `<${expected.tag}>`)}`;
  }
  if (actual.tag !== expected.tag) return `${path}: <${actual.tag}> ≠ <${expected.tag}>`;
  const names = [...new Set([...actual.attrs, ...expected.attrs].map(([name]) => name))].sort();
  for (const name of names) {
    const a = actual.attrs.find(([n]) => n === name)?.[1];
    const b = expected.attrs.find(([n]) => n === name)?.[1];
    if (a !== b) return `${path}: attribute ${name}: ${JSON.stringify(a ?? null)} ≠ ${JSON.stringify(b ?? null)}`;
  }
  const count = Math.max(actual.children.length, expected.children.length);
  const seen = new Map<string, number>();
  for (let i = 0; i < count; i += 1) {
    const a = actual.children[i];
    const b = expected.children[i];
    const name = label((a ?? b) as NormalNode);
    const index = seen.get(name) ?? 0;
    seen.set(name, index + 1);
    const childPath = `${path} > ${name}[${index}]`;
    if (!a || !b) return `${childPath}: ${a ? 'unexpected' : 'missing'} node`;
    const found = difference(a, b, childPath);
    if (found) return found;
  }
  return undefined;
}

/** Compares two renders as normalised trees, reporting the first difference. */
export function compareSvg(actual: string, expected: string): { equal: true } | { equal: false; difference: string } {
  const found = difference(parseSvg(actual), parseSvg(expected), 'svg');
  return found === undefined ? { equal: true } : { equal: false, difference: found };
}

function findDashboard(node: ParsedNode): ParsedElement | undefined {
  if (isElement(node) && node.tagName === 'section' && (node.attrs.find((a) => a.name === 'class')?.value.split(/\s+/) ?? []).includes('sp-dashboard')) return node;
  for (const child of 'childNodes' in node ? node.childNodes : []) {
    const found = findDashboard(child);
    if (found) return found;
  }
  return undefined;
}

/** Parses markup and returns the normalised tree of its dashboard `<section>`, charts included (DD-017). */
export function parseDashboard(markup: string): NormalElement {
  const section = findDashboard(parseFragment(markup));
  if (!section) throw new Error('No <section class="sp-dashboard"> in the markup.');
  return toTree(section, new Map(), { dashboard: true });
}

/** The normalised dashboard as text, one node per line: what a dashboard fixture's canonical file holds. */
export function normalizeDashboard(markup: string): string {
  const out: string[] = [];
  lines(parseDashboard(markup), 0, out);
  return out.join('\n');
}

/** Compares two dashboard renders as normalised trees, reporting the first difference (REQ-210). */
export function compareDashboard(actual: string, expected: string): { equal: true } | { equal: false; difference: string } {
  const found = difference(parseDashboard(actual), parseDashboard(expected), 'section');
  return found === undefined ? { equal: true } : { equal: false, difference: found };
}
