/**
 * Automated traceability (REQ-183, REQ-184): every `REQ-NNN` cited in a test name is reconciled
 * with the PRD's MUST set. A MUST that no test cites — and that the task list does not defer to
 * a later phase — is a blocking finding for the Analyze gate.
 *
 * Usage: pnpm traceability   (writes reports/traceability.md, exits non-zero on a blocking MUST)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const REQ = /REQ-\d{3}/g;

/** Every requirement defined in a PRD table row, with its priority (the row's last cell). */
export function requirementsIn(prd: string): Map<string, string> {
  const requirements = new Map<string, string>();
  for (const line of prd.split('\n')) {
    const cells = line.split('|').map((cell) => cell.trim());
    const id = cells[1];
    const priority = cells.at(-2);
    if (id && /^REQ-\d{3}$/.test(id) && priority && /^(MUST|SHOULD|COULD)$/.test(priority)) {
      requirements.set(id, priority);
    }
  }
  return requirements;
}

/**
 * Requirements cited in test names: the first string argument of `test(…)`, `it(…)`, their
 * `.skip` / `.only` forms, and the title call that follows `test.each(…)`.
 */
export function citedIn(source: string): Set<string> {
  const cited = new Set<string>();
  const title = /(?:\b(?:test|it)(?:\.(?:skip|only|concurrent))?|\))\s*\(\s*(['"`])((?:\\.|(?!\1)[^\\])*?)\1/g;
  for (const match of source.matchAll(title)) {
    for (const id of (match[2] ?? '').match(REQ) ?? []) cited.add(id);
  }
  return cited;
}

/** Requirements the task list defers to a later phase, ranges (`REQ-061 … REQ-092`) expanded. */
export function deferredIn(tasks: string): Set<string> {
  const deferred = new Set<string>();
  const section = tasks.split(/^## Deferred requirements/m)[1]?.split(/^## /m)[0] ?? '';
  for (const line of section.split('\n')) {
    const first = line.split('|')[1] ?? '';
    const range = /REQ-(\d{3})\s*(?:…|\.\.\.|–|-)\s*REQ-(\d{3})/.exec(first);
    if (range) {
      for (let n = Number(range[1]); n <= Number(range[2]); n += 1) deferred.add(`REQ-${String(n).padStart(3, '0')}`);
    } else {
      for (const id of first.match(REQ) ?? []) deferred.add(id);
    }
  }
  return deferred;
}

export interface CoverageReport {
  /** MUSTs cited by at least one test. */
  readonly covered: string[];
  /** MUSTs no test cites and no later phase owns: blocking for the Analyze gate (REQ-184). */
  readonly blocking: string[];
  /** MUSTs no test cites yet, deferred to a later phase by the task list. */
  readonly deferred: string[];
  /** Identifiers cited by a test but defined nowhere in the PRD. */
  readonly unknown: string[];
}

export function coverage(requirements: Map<string, string>, cited: Set<string>, deferred: Set<string>): CoverageReport {
  const musts = [...requirements].filter(([, priority]) => priority === 'MUST').map(([id]) => id).sort();
  return {
    covered: musts.filter((id) => cited.has(id)),
    blocking: musts.filter((id) => !cited.has(id) && !deferred.has(id)),
    deferred: musts.filter((id) => !cited.has(id) && deferred.has(id)),
    unknown: [...cited].filter((id) => !requirements.has(id)).sort(),
  };
}

const TEST_FILE = /\.(test|spec)\.(ts|tsx|mts|mjs|js)$/;

function testFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (['node_modules', 'dist', '.next', '.angular', '__golden__'].includes(entry.name)) return [];
    const path = join(dir, entry.name);
    return entry.isDirectory() ? testFiles(path) : TEST_FILE.test(entry.name) ? [path] : [];
  });
}

function main(): void {
  const root = fileURLToPath(new URL('../..', import.meta.url));
  const requirements = requirementsIn(readFileSync(join(root, 'specs/prd.md'), 'utf8'));
  const deferred = deferredIn(readFileSync(join(root, 'specs/tasks.md'), 'utf8'));
  const files = ['packages', 'tools', 'e2e'].flatMap((dir) => testFiles(join(root, dir)));
  const citations = new Map<string, string[]>();
  for (const file of files) {
    for (const id of citedIn(readFileSync(file, 'utf8'))) {
      citations.set(id, [...(citations.get(id) ?? []), relative(root, file)]);
    }
  }
  const report = coverage(requirements, new Set(citations.keys()), deferred);
  const musts = report.covered.length + report.blocking.length + report.deferred.length;
  const lines = [
    '# Traceability — REQ-183 / REQ-184',
    '',
    `Generated by \`pnpm traceability\` from ${files.length} test files. ${report.covered.length} of ${musts} MUST requirements are cited by at least one test; ${report.deferred.length} are deferred to later phases by \`specs/tasks.md\`; **${report.blocking.length} blocking**.`,
    '',
    '## Blocking — MUST with no test (REQ-184)',
    '',
    ...(report.blocking.length === 0 ? ['None.'] : report.blocking.map((id) => `- ${id}`)),
    '',
    '## Deferred to a later phase',
    '',
    report.deferred.join(', ') || 'None.',
    '',
    '## Cited but undefined',
    '',
    report.unknown.join(', ') || 'None.',
    '',
    '## Covered',
    '',
    '| REQ | Priority | Test files |',
    '|---|---|---|',
    ...[...citations.keys()]
      .filter((id) => requirements.has(id))
      .sort()
      .map((id) => `| ${id} | ${requirements.get(id)} | ${[...new Set(citations.get(id))].join('<br>')} |`),
    '',
  ];
  mkdirSync(join(root, 'reports'), { recursive: true });
  writeFileSync(join(root, 'reports/traceability.md'), lines.join('\n'));
  console.log(`traceability · ${report.covered.length}/${musts} MUST covered · ${report.deferred.length} deferred · ${report.blocking.length} blocking`);
  for (const id of report.blocking) console.error(`blocking  ${id} is a MUST with no test citing it (REQ-184)`);
  for (const id of report.unknown) console.error(`unknown   ${id} is cited by a test but not defined in the PRD`);
  process.exit(report.blocking.length === 0 && report.unknown.length === 0 ? 0 : 1);
}

if (process.argv[1]?.endsWith('traceability.ts')) main();
