import { defineConfig } from 'tsup';

const shared = {
  format: ['esm'] as const,
  target: 'es2022',
  dts: true,
  sourcemap: true,
  // Rollup's treeshake pass drops module-level directives; esbuild already tree-shakes.
  treeshake: false,
  external: ['react', 'react-dom', 'react/jsx-runtime', '@silverpoint/core', '@silverpoint/grounds'],
};

// Client entries carry the "use client" marker; server entries must not (REQ-104).
export default defineConfig([
  {
    ...shared,
    clean: true,
    entry: {
      index: 'src/index.ts',
      'line-chart': 'src/line-chart-entry.ts',
      'bullet-chart': 'src/bullet-chart.tsx',
      'pyramid-chart': 'src/pyramid-chart.tsx',
      'heatmap-chart': 'src/heatmap-chart.tsx',
      'treemap-chart': 'src/treemap-chart.tsx',
      'sankey-chart': 'src/sankey-chart.tsx',
      'activity-grid': 'src/activity-grid.tsx',
      'step-chart': 'src/step-chart.tsx',
      'sparkline-rows': 'src/sparkline-rows.tsx',
      'kpi-card': 'src/kpi-card.tsx',
      'bar-chart': 'src/bar-chart.tsx',
      'stacked-bar-chart': 'src/stacked-bar-chart.tsx',
      'composed-chart': 'src/composed-chart.tsx',
      'waterfall-chart': 'src/waterfall-chart.tsx',
      'funnel-chart': 'src/funnel-chart.tsx',
      'candlestick-chart': 'src/candlestick-chart.tsx',
      'area-chart': 'src/area-chart.tsx',
      'range-band-chart': 'src/range-band-chart.tsx',
      'stream-chart': 'src/stream-chart.tsx',
      'scatter-chart': 'src/scatter-chart.tsx',
      'bubble-chart': 'src/bubble-chart.tsx',
    },
    banner: { js: "'use client';" },
  },
  {
    ...shared,
    entry: {
      'server/line-chart': 'src/server/line-chart.tsx',
      'server/bullet-chart': 'src/server/bullet-chart.tsx',
      'server/pyramid-chart': 'src/server/pyramid-chart.tsx',
      'server/heatmap-chart': 'src/server/heatmap-chart.tsx',
      'server/treemap-chart': 'src/server/treemap-chart.tsx',
      'server/sankey-chart': 'src/server/sankey-chart.tsx',
      'server/activity-grid': 'src/server/activity-grid.tsx',
      'server/step-chart': 'src/server/step-chart.tsx',
      'server/sparkline-rows': 'src/server/sparkline-rows.tsx',
      'server/kpi-card': 'src/server/kpi-card.tsx',
      'server/bar-chart': 'src/server/bar-chart.tsx',
      'server/stacked-bar-chart': 'src/server/stacked-bar-chart.tsx',
      'server/composed-chart': 'src/server/composed-chart.tsx',
      'server/waterfall-chart': 'src/server/waterfall-chart.tsx',
      'server/funnel-chart': 'src/server/funnel-chart.tsx',
      'server/candlestick-chart': 'src/server/candlestick-chart.tsx',
      'server/area-chart': 'src/server/area-chart.tsx',
      'server/range-band-chart': 'src/server/range-band-chart.tsx',
      'server/stream-chart': 'src/server/stream-chart.tsx',
      'server/scatter-chart': 'src/server/scatter-chart.tsx',
      'server/bubble-chart': 'src/server/bubble-chart.tsx',
    },
  },
]);
