/** Writes reports/path-weight.md: the T-027 measurement, reproducible from the repository. */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PATH_BYTE_BUDGET } from '@silverpoint/core';
import { AFTER_LINE_CHART } from '../visual-gate/catalog';
import { measureChart, measureDenseCard, measureLineChart } from './measure';

const kb = (bytes: number) => `${(bytes / 1024).toFixed(1)} KiB (${bytes} B)`;
const rows: string[] = [];
for (const size of ['sm', 'md', 'lg'] as const) {
  const line = measureLineChart(size);
  rows.push(`| LineChart, demo dataset, ${size} | ${kb(line.precision)} | ${kb(line.ink)} | — |`);
}
for (const bars of [6, 12]) {
  const card = measureDenseCard(bars);
  rows.push(`| Dense card, ${bars} cross-hatched bars + tone-3 area | — | ${kb(card.tile)} | ${kb(card.perShape)} |`);
}
for (const entry of AFTER_LINE_CHART) {
  for (const size of ['sm', 'md', 'lg'] as const) {
    const weight = measureChart(entry.recipe, size);
    const over = (bytes: number) => (bytes > PATH_BYTE_BUDGET ? ' **over**' : '');
    rows.push(`| ${entry.chart}, demo dataset, ${size} | ${kb(weight.precision)} | ${kb(weight.tile)}${over(weight.tile)} | ${kb(weight.perShape)}${over(weight.perShape)} |`);
  }
}
const report = `# Path weight — T-027, T-044

Generated by \`pnpm --filter @silverpoint/path-weight report\`. Budget: ${kb(PATH_BYTE_BUDGET)} of \`d\` data per chart (PRD NFR §7).

| Chart | precision | ink, \`hatchFill: 'tile'\` | ink, \`hatchFill: 'per-shape'\` |
|---|---|---|---|
${rows.join('\n')}

## Findings (T-044, the open question of TD §10)

- **The 40 KB budget is confirmed.** With the tile fill every Phase 1 chart stays far under it at
  every size; the heaviest is the activity grid, whose cost is its 182 cell outlines, not its
  hatching — the tiles are a fixed ~1 KB per tonal level.
- **Per-shape hatching does not fit the matrix families.** The heatmap and the activity grid pass
  40 KB at \`lg\` with \`hatchFill: 'per-shape'\`, and SP011 says so. That is DD-007's reason for the
  tile, now measured on the charts where the tile helps least; \`per-shape\` stays an opt-in.
`;
const out = fileURLToPath(new URL('../../reports/path-weight.md', import.meta.url));
mkdirSync(fileURLToPath(new URL('../../reports', import.meta.url)), { recursive: true });
writeFileSync(out, report);
console.log(report);
