/** Writes reports/path-weight.md: the T-027 measurement, reproducible from the repository. */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PATH_BYTE_BUDGET } from '@silverpoint/core';
import { measureDenseCard, measureLineChart } from './measure';

const kb = (bytes: number) => `${(bytes / 1024).toFixed(1)} KiB (${bytes} B)`;
const rows: string[] = [];
for (const size of ['sm', 'md', 'lg'] as const) {
  const line = measureLineChart(size);
  rows.push(`| LineChart, demo dataset, ${size} | ${kb(line.precision)} | ${kb(line.ink)} | — |`);
}
for (const bars of [6, 12]) {
  const card = measureDenseCard(bars);
  rows.push(`| Dense card, ${bars} cross-hatched bars + tone-3 area | — | ${kb(card.tile)} | ${kb(card.perShape)} |`);
}
const report = `# Path weight — T-027

Generated by \`pnpm --filter @silverpoint/path-weight report\`. Budget: ${kb(PATH_BYTE_BUDGET)} of \`d\` data per chart (PRD NFR §7).

| Chart | precision | ink, \`hatchFill: 'tile'\` | ink, \`hatchFill: 'per-shape'\` |
|---|---|---|---|
${rows.join('\n')}
`;
const out = fileURLToPath(new URL('../../reports/path-weight.md', import.meta.url));
mkdirSync(fileURLToPath(new URL('../../reports', import.meta.url)), { recursive: true });
writeFileSync(out, report);
console.log(report);
