/**
 * Writes the fixture matrix and its canonical renders.
 *
 * Usage: pnpm --filter @silverpoint/visual-gate canonical
 *
 * Regenerating a canonical file changes the normalised SVG output, which is never a patch
 * (API Spec §13): commit it deliberately, with a changeset that says so.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CATALOG } from './catalog';
import { canonicalFor, FIXTURES_DIR, fixtureId, SIZES, type Fixture } from './fixtures';

/** The card each chart's fixtures draw around its demo dataset. */
const CARDS: Readonly<Record<string, Readonly<Record<string, unknown>>>> = {
  LineChart: { title: 'Throughput per hour', badge: 'Live', value: 88, unit: 'requests', footerLeft: '00–22 h', footerRight: 'silverpoint' },
  BulletChart: { title: 'Quarter targets', badge: 'Q2', footerLeft: '0–100', footerRight: 'silverpoint' },
  PyramidChart: { title: 'Headcount by level', badge: '2026', footerLeft: 'width in %', footerRight: 'silverpoint' },
  HeatmapChart: { title: 'Load by weekday', badge: 'Week 26', footerLeft: 'of 100', footerRight: 'silverpoint' },
  TreemapChart: { title: 'Traffic sources', badge: 'June', footerLeft: 'share of visits', footerRight: 'silverpoint' },
  SankeyChart: { title: 'Visitor flow', badge: 'June', footerLeft: 'visits', footerRight: 'silverpoint' },
  ActivityGrid: { title: 'Contributions', badge: '26 weeks', footerLeft: 'Jan–Jun 2026', footerRight: 'silverpoint' },
};

/** The PR matrix: every catalog chart × 2 modes × 4 substrates at `md` (Data Model §5). */
function matrix(): Fixture[] {
  const fixtures: Fixture[] = [];
  for (const { chart, req, slug } of CATALOG) {
    for (const mode of ['ink', 'precision'] as const) {
      for (const substrate of ['cream', 'green', 'blue', 'ochre']) {
        const cell = { chart, ground: 'silverpoint', substrate, mode, hatchFill: 'tile', size: SIZES.md } as const;
        const id = fixtureId(cell);
        fixtures.push({
          ...cell,
          id,
          req,
          seed: 1592,
          props: CARDS[chart] ?? {},
          data: null,
          canonical: `${slug}/${id}.canonical.txt`,
        });
      }
    }
  }
  return fixtures;
}

const fixtures = matrix();
for (const fixture of fixtures) {
  const json = join(FIXTURES_DIR, dirname(fixture.canonical), `${fixture.id}.fixture.json`);
  mkdirSync(dirname(json), { recursive: true });
  writeFileSync(json, `${JSON.stringify(fixture, null, 2)}\n`);
  writeFileSync(join(FIXTURES_DIR, fixture.canonical), canonicalFor(fixture));
  console.log(`wrote ${fixture.id}`);
}

// The example apps read the matrix from a generated module: no filesystem access in a browser.
const harness = fileURLToPath(new URL('../../examples/harness/fixtures.generated.js', import.meta.url));
const embedded = [...fixtures]
  .sort((a, b) => (a.id < b.id ? -1 : 1))
  .map(({ canonical: _canonical, data, ...fixture }) => ({
    ...fixture,
    rows: data === null ? null : JSON.parse(readFileSync(join(FIXTURES_DIR, data), 'utf8')),
  }));
writeFileSync(
  harness,
  `// Generated by tools/visual-gate/canonical.ts — do not edit.\nexport const FIXTURES = ${JSON.stringify(embedded, null, 2)};\n`,
);
console.log(`wrote ${harness}`);
